// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard";
  };
  "./modules/login.tsx": {
    id: "modules/login";
    page: "/";
  };
  "./modules/dashboard.tsx": {
    id: "modules/dashboard";
    page: "/dashboard";
  };
};